version: "3.7"

services:
  auth-postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
